# coding: utf-8

"""
    CE-RISE Hex Core Service API

    Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ce_rise_hex_core_sdk.models.record import Record

class TestRecord(unittest.TestCase):
    """Record unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Record:
        """Test Record
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Record`
        """
        model = Record()
        if include_optional:
            return Record(
                id = '',
                model = '',
                version = '',
                payload = { }
            )
        else:
            return Record(
                id = '',
                model = '',
                version = '',
                payload = { },
        )
        """

    def testRecord(self):
        """Test Record"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
