# coding: utf-8

"""
    CE-RISE Hexagonal Core Service API

    Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ce_rise_hex_core_sdk.api.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_health(self) -> None:
        """Test case for health

        Liveness probe
        """
        pass

    def test_metrics(self) -> None:
        """Test case for metrics

        Prometheus metrics
        """
        pass

    def test_ready(self) -> None:
        """Test case for ready

        Readiness probe
        """
        pass

    def test_status(self) -> None:
        """Test case for status

        Runtime status
        """
        pass


if __name__ == '__main__':
    unittest.main()
