# coding: utf-8

"""
    CE-RISE Hexagonal Core Service API

    Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ce_rise_hex_core_sdk.api.models_api import ModelsApi


class TestModelsApi(unittest.TestCase):
    """ModelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModelsApi()

    def tearDown(self) -> None:
        pass

    def test_create_record(self) -> None:
        """Test case for create_record

        Validate and create a record
        """
        pass

    def test_query_records(self) -> None:
        """Test case for query_records

        Query records for a model version
        """
        pass

    def test_validate_model_payload(self) -> None:
        """Test case for validate_model_payload

        Validate payload against model rules
        """
        pass


if __name__ == '__main__':
    unittest.main()
