# coding: utf-8

"""
    CE-RISE Hex Core Service API

    Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ce_rise_hex_core_sdk.api.discovery_api import DiscoveryApi


class TestDiscoveryApi(unittest.TestCase):
    """DiscoveryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DiscoveryApi()

    def tearDown(self) -> None:
        pass

    def test_list_models(self) -> None:
        """Test case for list_models

        List available model versions
        """
        pass


if __name__ == '__main__':
    unittest.main()
