# coding: utf-8

"""
    CE-RISE Hex Core Service API

    Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ce_rise_hex_core_sdk.models.models_response import ModelsResponse

class TestModelsResponse(unittest.TestCase):
    """ModelsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsResponse:
        """Test ModelsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsResponse`
        """
        model = ModelsResponse()
        if include_optional:
            return ModelsResponse(
                models = [
                    ce_rise_hex_core_sdk.models.model_version.ModelVersion(
                        id = '', 
                        version = '', )
                    ]
            )
        else:
            return ModelsResponse(
                models = [
                    ce_rise_hex_core_sdk.models.model_version.ModelVersion(
                        id = '', 
                        version = '', )
                    ],
        )
        """

    def testModelsResponse(self):
        """Test ModelsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
