# coding: utf-8

"""
    CE-RISE Hexagonal Core Service API

    Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ce_rise_hex_core_sdk.models.model_version import ModelVersion

class TestModelVersion(unittest.TestCase):
    """ModelVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelVersion:
        """Test ModelVersion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelVersion`
        """
        model = ModelVersion()
        if include_optional:
            return ModelVersion(
                id = '',
                version = ''
            )
        else:
            return ModelVersion(
                id = '',
                version = '',
        )
        """

    def testModelVersion(self):
        """Test ModelVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
