# coding: utf-8

"""
    CE-RISE Hex Core Service API

    Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ce_rise_hex_core_sdk.models.ready_response import ReadyResponse

class TestReadyResponse(unittest.TestCase):
    """ReadyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReadyResponse:
        """Test ReadyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReadyResponse`
        """
        model = ReadyResponse()
        if include_optional:
            return ReadyResponse(
                status = 'ready'
            )
        else:
            return ReadyResponse(
                status = 'ready',
        )
        """

    def testReadyResponse(self):
        """Test ReadyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
