# coding: utf-8

"""
    CE-RISE Hex Core Service API

    Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "ce-rise-hex-core-sdk"
VERSION = "0.0.2"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="CE-RISE Hex Core Service API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "CE-RISE Hex Core Service API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.
    """,  # noqa: E501
    package_data={"ce_rise_hex_core_sdk": ["py.typed"]},
)
