# coding: utf-8

"""
    CE-RISE Hex Core Service API

    Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ce_rise_hex_core_sdk.models.record_query_condition import RecordQueryCondition
from ce_rise_hex_core_sdk.models.record_query_sort import RecordQuerySort
from typing import Optional, Set
from typing_extensions import Self

class RecordQueryFilter(BaseModel):
    """
    Canonical backend query dialect shared across record store adapters.
    """ # noqa: E501
    where: List[RecordQueryCondition] = Field(description="AND-only list of query predicates.")
    sort: Optional[List[RecordQuerySort]] = Field(default=None, description="Optional list of sort directives applied in order.")
    limit: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Maximum number of records to return.")
    offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Zero-based row offset for pagination.")
    __properties: ClassVar[List[str]] = ["where", "sort", "limit", "offset"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecordQueryFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in where (list)
        _items = []
        if self.where:
            for _item_where in self.where:
                if _item_where:
                    _items.append(_item_where.to_dict())
            _dict['where'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sort (list)
        _items = []
        if self.sort:
            for _item_sort in self.sort:
                if _item_sort:
                    _items.append(_item_sort.to_dict())
            _dict['sort'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecordQueryFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "where": [RecordQueryCondition.from_dict(_item) for _item in obj["where"]] if obj.get("where") is not None else None,
            "sort": [RecordQuerySort.from_dict(_item) for _item in obj["sort"]] if obj.get("sort") is not None else None,
            "limit": obj.get("limit"),
            "offset": obj.get("offset")
        })
        return _obj


